Feat/2 sign
FOREGG-DEV/FOREGG_ANDROID_COMPOSE pull request #5
Opened 2024-08-07 06:32 UTC by rudtjr1106

## 이슈 번호
2번

## 작업내용
온보딩 (임시 - 이미지가 변경될 예정이라고 하십니다.), 로그인 및 회원가입 (남, 여) 기능 추가하였습니다. #아직 홈으로 연결은 되어있지 않습니다!

추가로 공통으로 사용하는 컴포넌트 일부 제작했습니다!(TopBar, Button)
사용법은 아래와 같습니다!
```
@Composable
fun TopBar(
    leftItemType : TopBarLeftType = TopBarLeftType.NONE,
    middleItemType : TopBarMiddleType = TopBarMiddleType.NONE,
    rightItemType : TopBarRightType = TopBarRightType.NONE,
    leftBtnClicked : () -> Unit = {},
    middleText : String = "",
    rightBtnClicked : () -> Unit = {},
)
```
leftItemType : BACK(뒤로가기 이미지), LOGO(로고 이미지), CLOSE(X 이미지)
middleItemType : LOGO(로고 이미지), TEXT( 글자 아래 영상에서 [회원가입] 같은 키워드)
rightItemType : SKIP(Skip 텍스트), DAILY_RECORD(하루기록 버튼), CREATE(생성 + 버튼), CHECK(원형 v표시 버튼), DELETE(삭제 쓰레기통 버튼)
leftBtnClicked : 왼쪽에 위치한 버튼 클릭시 동작하는 함수
middleText : (middleItemType이 TEXT일 경우에만) 키워드 명
rightBtnClicked : 오른쪽에 위치한 버튼 클릭시 동작하는 함수

기본값은 NONE으로 설정되어있어 만약 아무것도 필요 없다면 파라미터로 넘기지 않으셔도 되며, 변경될 가능성이 높습니다!

```
@Composable
fun BlankBtn(
    modifier: Modifier = Modifier,
    onClickBtn : () -> Unit = {},
    radius : Dp = 8.dp,
    text : String = "테스트",
    textStyle: TextStyle = HuggTypography.btn,
    textColor : Color = Gs70,
    contentPadding : PaddingValues = PaddingValues(horizontal = 0.dp, vertical = 16.dp)
)

@Composable
fun FilledBtn(
    modifier: Modifier = Modifier,
    onClickBtn : () -> Unit = {},
    radius : Dp = 8.dp,
    text : String = "테스트",
    textStyle: TextStyle = HuggTypography.btn,
    textColor : Color = White,
    contentPadding : PaddingValues = PaddingValues(horizontal = 0.dp, vertical = 16.dp)
)
```
<img width="508" alt="스크린샷 2024-08-07 오후 3 29 33" src="https://github.com/user-attachments/assets/90532b3c-df49-426c-b815-7509eae764db">

위 컴포넌트에 대한 함수입니다. 자세한 내용은 feature -> component -> HuggButton.kt 에서 확인 가능합니다!

## 결과물

https://github.com/user-attachments/assets/369cf232-4797-4568-b171-7e028a05e491

(여자)

https://github.com/user-attachments/assets/09cf7cab-5d33-4a12-b998-29a6830fd48a

(남자)

## 리뷰어에게 추가로 요구하는 사항(선택)
최대한 state hoisting을 신경쓰며 제작하였으나 부족한 부분이 있는지 검토 부탁드리겠습니다! viewmodel 코드는 거의 기존 코드를 사용하였습니다.

추가로 현재 저의 에뮬에서는 onboarding pager가 렉이 좀 걸리는 것 같습니다! 요거 확인 부탁드리며 똑같이 렉이 걸린다면 개선할 수 있는 방법 찾아보겠습니다!

2024-08-15 14:35 UTC, dogmania requested changes
고생하셨습니다! 상태 호이스팅 잘 적용해서 구현하신 것 같습니다. 제가 남긴 코멘트 중에 틀린 것이 있다면 알려주세요!

2024-08-15 14:35 UTC, dogmania commented on feature/sign/src/main/java/com/hugg/sign/inputSsn/InputSsnPageState.kt
> +) : PageState
이 부분을 리스트로 저장하는 것을 어떨까요?

2024-08-15 14:35 UTC, dogmania commented on feature/sign/src/main/java/com/hugg/sign/inputSsn/InputSsnScreen.kt
> +        Spacer(modifier = Modifier.width(2.dp))
PageState를 리스트로 변경하면 주민번호 앞자리는 반복문으로 처리하고 뒤에 한자리만 그대로 두면 될 것 같습니다!

2024-08-15 14:35 UTC, dogmania commented on feature/sign/src/main/java/com/hugg/sign/inputSsn/InputSsnScreen.kt
> +                .background(Color(0xFFF2F2F2), shape = RoundedCornerShape(4.dp))
여기도 색상 수정해주시면 감사하겠습니다!

2024-08-15 14:35 UTC, dogmania commented on feature/sign/src/main/java/com/hugg/sign/inputSsn/InputSsnScreen.kt
> +    val focusRequesters = remember { List(7) { FocusRequester() } }
FocusRequester라는 것이 있는지 처음 알았네요! UX 개선할 때 유용하게 사용할 수 있을 것 같습니다! 새로 알아갑니다

2024-08-15 14:35 UTC, dogmania commented on feature/sign/src/main/java/com/hugg/sign/inputSsn/InputSsnViewModel.kt
> +        val ssn = uiState.value.run {
ssn을 리스트로 변경하면 이 코드는 다음과 같이 변경할 수 있을 것 같습니다

```
    val ssn = uiState.value.ssn.joinToString(separator = "").run {
        substring(0, 6) + "-" + substring(6, 7)
    }
```

2024-08-15 14:35 UTC, dogmania commented on feature/sign/src/main/java/com/hugg/sign/maleSignUp/MaleSignUpScreen.kt
> +            )
혹시 이거는 어디에 사용되는지 알 수 있을까요??
제가 이해하기로는 온보딩에서 현재 페이지 나타내는 점인 거 같은데 피그마에 남편 회원가입 화면에는 없는 것 같아서요

2024-08-15 14:35 UTC, dogmania commented on feature/sign/src/main/java/com/hugg/sign/onboarding/OnboardingScreen.kt
> +}
이 함수들을 뷰모델이 아닌 여기에 구현한 이유가 있을까요??

2024-08-15 14:35 UTC, dogmania commented on feature/src/main/java/com/hugg/feature/component/HuggButton.kt
저도 개발할 때 이 컴포넌트 활용해서 잘 사용하겠습니다!

2024-08-15 14:35 UTC, dogmania commented on feature/src/main/java/com/hugg/feature/component/HuggSnackBar.kt
> +           .background(color = Color(0xCC2C2C2C), shape = RoundedCornerShape(8.dp)),
여기도 색상 수정해주실 수 있을까요?

2024-08-15 15:02 UTC, rudtjr1106 commented on feature/main/src/main/java/com/hugg/main/NavExpansions.kt
> +        }
확인했습니다! NavExpansions에 있는 내용은 모두 타입 명시해뒀습니다! 앞으로 람다식에 가능하면 type을 명시해보도록 하겠습니다!

2024-08-15 15:14 UTC, rudtjr1106 commented on feature/main/src/main/java/com/hugg/main/NavExpansions.kt
> +}
흠... 확실히 나쁘지 않은 것 같습니다! 
저는` route = "${NavRoutes.TaskDetailScreen.route}/{id}"` 보단 
`route = Routes.Sign.MALE_SIGN_UP`
요런 느낌으로 보는게 좀 더 좋을 것 같아서 위 코드로 제작하긴 했습니다!
다만 큰 프로젝트에서는 형님께서 말씀해주신 sealed class로 타입의 안정성 등 이점을 챙기는게 좋을 것 같네용

data object TaskDetailScreen: NavRoutes("taskDetailScreen/{id}")
요렇게 사용하면 서로의 니즈를 맞출 수 있을 것 같습니다! 형님 방식대로 수정 진행하겠습니다!

2024-08-15 15:30 UTC, rudtjr1106 commented on feature/sign/src/main/java/com/hugg/sign/femaleSignUp/spouseCodeFemale/SpouseCodeFemaleViewModel.kt
넵 이번 코드에서는 UseCase는 사용하지 않습니다!
이유는 간단하게 불필요한 것 같아서용 ㅎㅎ.....
원래 UseCase에서 코드를 가공하거나 이것저것 ViewModel에서 하기 껄끄러운 일들을 처리하면 좋지만 현재 저희 코드에서는 그냥 데이터를 받아와서 넘겨주는 코드라 repository에 직접 접근하는게 더 좋을 것 같다고 판단했습니당
이렇게 하면 귀찮게 너무 많은 UseCase를 만들지도, 생성자에 추가할 필요가 없어 코드가 좀 더 클린해지더라구용

2024-08-15 15:34 UTC, rudtjr1106 commented on feature/sign/src/main/java/com/hugg/sign/femaleSignUp/startSurgery/SurgeryStartScreen.kt
> +            viewModel.selectStartDate("$year-$formattedMonth-$formattedDay")
TimeFormatter에 

```
    fun getDatePickerDashDate(year : Int, month : Int, day : Int) : String {
        val formattedMonth = String.format("%02d", month + 1)
        val formattedDay = String.format("%02d", day)
        return "$year-$formattedMonth-$formattedDay"
    }
```
위와 같이 구현해뒀습니다! 혹시라도 DatePicker쓰시게 된다면 날짜는 요걸로 받아오시면 될 것 같습니당

2024-08-15 15:38 UTC, rudtjr1106 commented on feature/sign/src/main/java/com/hugg/sign/femaleSignUp/surgeryCount/SurgeryCountScreen.kt
> +                        color = if (uiState.count == 0) Color(0xFFF2F2F2) else MainNormal,
Disabled 라는 명칭으로 정의했습니다!

2024-08-15 15:59 UTC, rudtjr1106 commented on feature/sign/src/main/java/com/hugg/sign/inputSsn/InputSsnViewModel.kt
> +        val ssn = uiState.value.run {
오 요거 잊고 있었네요 감사합니다!!

2024-08-15 16:00 UTC, rudtjr1106 commented on feature/sign/src/main/java/com/hugg/sign/maleSignUp/MaleSignUpScreen.kt
> +            )
피그마 [UI --- 진행중] 페이지 보시면 회원가입에 인디케이터가 추가되었습니다! 그래서 공통으로 하나 만들었습니당

2024-08-15 16:08 UTC, rudtjr1106 commented on feature/sign/src/main/java/com/hugg/sign/onboarding/OnboardingScreen.kt
> +}
위 함수들은 모두 context를 사용하고 있습니다! 
context는 생명주기와 연관이 있기 때문에 Viewmodel에서 사용하게 된다면 메모리 누수, 자칫하다 에러까지 발생할 수 있어서 요기 Screen에서 사용했습니다!

2024-08-16 07:40 UTC, dogmania commented on feature/main/src/main/java/com/hugg/main/NavExpansions.kt
> +}
네 감사합니다!

2024-08-16 07:41 UTC, dogmania commented on feature/sign/src/main/java/com/hugg/sign/femaleSignUp/spouseCodeFemale/SpouseCodeFemaleViewModel.kt
네 확인했습니다!

2024-08-16 07:41 UTC, dogmania commented on feature/sign/src/main/java/com/hugg/sign/femaleSignUp/startSurgery/SurgeryStartScreen.kt
> +            viewModel.selectStartDate("$year-$formattedMonth-$formattedDay")
네 감사합니다!

2024-08-16 07:41 UTC, dogmania commented on feature/sign/src/main/java/com/hugg/sign/femaleSignUp/surgeryCount/SurgeryCountScreen.kt
> +                        color = if (uiState.count == 0) Color(0xFFF2F2F2) else MainNormal,
네 감사합니다!

2024-08-16 07:42 UTC, dogmania commented on feature/sign/src/main/java/com/hugg/sign/maleSignUp/MaleSignUpScreen.kt
> +            )
네 감사합니다!

2024-08-16 07:47 UTC, dogmania commented on feature/sign/src/main/java/com/hugg/sign/onboarding/OnboardingScreen.kt
> +}
제가 아직 확인해보지는 못했지만 저는 Context와 UserApiClient 제공 함수를 AppModule에 정의하고 Hilt를 통해 주입받아서 뷰모델에 구현하면 어떨지 생각해봤습니다! 메모리 누수 문제는 생각해본 적이 없는데 하나 또 알아갑니다

2024-08-16 07:49 UTC, dogmania commented
네 변경사항 모두 확인했습니다. Context와 UserApiClient 관련해서는 제가 좀 더 공부해보겠습니다. 고생하셨습니다!

2024-08-16 07:50 UTC, dogmania approved these changes

2024-08-16 08:02 UTC, merged